backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "people"
    label: "People"
    folder: "src/"  # Ruta al directorio que contiene people.json
    create: false  # Desactivar la creación de nuevos archivos, ya que no necesitas crear nuevos archivos para cada persona
    slug: "{{slug}}"  # Puedes ajustar esto según la estructura de tus datos
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Image 1", name: "img1", widget: "image" }
      - { label: "Image 2", name: "img2", widget: "image" }
