backend:
  name: git-gateway
  branch: PruebaGatsbyMd  # Asegúrate de que estás utilizando la rama correcta

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "people"
    label: "People"
    extension: "json"  # Utiliza la extensión json en lugar de md
    format: "json"     # Especifica el formato como json
    folder: "src/jsons"      # Ruta al directorio que contiene people.json
    create: true       # Desactivar la creación de nuevos archivos, ya que no necesitas crear nuevos archivos para cada persona
    slug: "{{slug}}"   # Puedes ajustar esto según la estructura de tus datos
    editor:
      preview: false   # Desactiva la vista previa del editor para evitar conflictos con JSON
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Image 1", name: "img1", widget: "image" }
      - { label: "Image 2", name: "img2", widget: "image" }
